### ISSUE TITLE
Ui WAY too zoomed in

### ISSUE THREAD

**Issue by HigherFPS** [convexvr/sims4-vr#6]
Can't see the Ui in-game at all. Imagine it as sitting right up against your monitor, can only see the main game, none of the Ui around it. Changing res/refresh rate doesn't make any difference.
Might just be bc no VorpX.

**Comment by convexvr** [comment]
Yeah that is how the "new" version of the plugin is.
In the old version of the mod that used the vorpX API one could set the UI size using the vorpX settings, but that was never a great experience.

The current "plan" is to decouple the "actions" UI from the VR tracking. And make the UI on the sides appear like some type of floating "screen" in the VR experience.

But before that is done a new stero rendering setup must be implemented. The current setup of alternating each frame left and right is a terrible experience.

I built this mod mostly cause i wanted to learn how VR works. I think the fact that you can walk around with your sims is pretty cool but the effort needed to implement the "plans" i mentioned and polish the mod to something user friendly is not something i have time for, especially when i cant charge anything for the mod (due to EA license rules). That said I would love it if there was some other contributors. It is open source for a reason.

**Comment by AnimeshniiGamer** [comment]
I launched the game with this mod and yes.The image in VR glasses is transmitted only partially to one eye...the second eye sometimes lags, and sometimes it works.But this mod is truly unique.I look forward to further updates, thank you for the opportunity to acquire a new gaming experience, given the fact that I am an ardent fan of The Sims 4.And playing it in Vr will be a huge success in the gaming experience
